apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: manual
